#!/bin/sh

#ADD CODERUNNER EXTENSION
#DESIGNED TO BE USED FROM THE MOODLE TEST SEVER

#change things according to your settings
BRANCH=MOODLE_26_STABLE
PATH_TO_MOODLE=/data/www/html

#Install Coderunner
cd $PATH_TO_MOODLE/local
#clone from github
git clone https://github.com/trampgeek/CodeRunner.git
#cd CodeRunner
#sudo ./install

#change to moodle directory
cd $PATH_TO_MOODLE
git commit -am "Cloned CodeRunner from github"
git tag -a version1+coderunner -m 'version1 with CodeRunner'

cd $PATH_TO_MOODLE
git push --tags production $BRANCH

echo "<<<<<< All done >>>>>"