#!/bin/sh
echo "*** Mount the folders via sshfs ***"
echo "H_DRIVE password"
sshfs u1374759@myfiles.warwick.ac.uk:H_Drive $HOME/hdrive/
echo "moodle-test password"
sshfs admin@moodle-test.warwick.ac.uk:/data/www/html $HOME/moodle-test/
echo "mahara-test password"
sshfs admin@mahara-test.warwick.ac.uk:/data/www/html $HOME/mahara-test/
echo "moodleX password"
sshfs admin@moodlex.warwick.ac.uk:/data/www/html $HOME/moodlex/
echo "*** All done ***"
