#!/bin/sh

#clone the project in the web root directory
cd /data/www/html
git clone https://github.com/trampgeek/jobe.git

cd /data/www/html/jobe
#add actechlab remote
git remote add actechlab git@actechlab.warwick.ac.uk:moodle/jobe.git
git push actechlab
