#!/bin/sh
cd $HOME/public_html
#register the upstream remote
#if it doesn't already exists
git remote add upstream git://git.moodle.org/moodle.git
#register the origin remote
#if it doesn't already exists
git remote add origin git@github.com:digitalquest/moodle.git

#keep the standard Moodle branches at actechlab Github repository synced with the upstream repository.
#oringin is git@actechlab.warwick.ac.uk:uxxxxxxxx/moodle.git
#upstream is git://git.moodle.org/moodle.git
#git fetch upstream
#for BRANCH in MOODLE_{19..27}_STABLE master; do
#       git push origin refs/remotes/upstream/$BRANCH:$BRANCH
#done
