#!/bin/sh

#change things according to your settings
BRANCH=MOODLE_26_STABLE
PATH_TO_MOODLE=/data/www/html
WEB_SERVER_USER=apache
MOODLE_DATA=/data/www/moodledata

cd $PATH_TO_MOODLE
git init
#add moodle repository
git remote add moodle git://git.moodle.org/moodle.git
git pull moodle $BRANCH

#Secure the Moodle files
#chown -R root $PATH_TO_MOODLE
chmod -R 0755 $PATH_TO_MOODLE
find $PATH_TO_MOODLE -type f -exec chmod 0644 {} \;

#Create the (moodledata) data directory
mkdir $MOODLE_DATA
chmod 0777 $MOODLE_DATA

echo "<<<< ALL DONE >>>>"