#!/bin/sh

#clone the project in the web root directory
cd /data/www/html
git clone https://github.com/trampgeek/jobe.git

cd /data/www/html/jobe

#Installation is performed by the install script, which must be run as root 
#so that it can add the required jobe run users (jobe00, jobe01, etc) 
#and set-up a jobe-sudoers file in /etc/sudoers.d 
#that allows the web server to execute the runguard program as root 
#and to kill any residual jobe processes from the run.
sudo ./install