#!/bin/sh

#SETS UP THE PRODUCTION REPOSITORY
#DESIGNED TO BE USED FROM THE MOODLE TEST SEVER
BRANCH=MOODLE_26_STABLE

#cd to <moodle main> directory.
#change things according to your settings
cd data/www/html
#add the production remote repository
git add remote production git@actechlab.warwick.ac.uk:techteam/moodle_production.git

#
git checkout $BRANCH
git tag -a version1 -m "first copy from test server to be used on the production machine" 
git push production $BRANCH

#Install Coderunner
cd local
#clone from github
git clone https://github.com/trampgeek/CodeRunner.git
#cd CodeRunner
#sudo ./install

#change to moodle directory
cd data/www/html
git commit -am "Cloned CodeRunner from github"
git tag -a version1+coderunner -m 'version1 with CodeRunner'

#install Jobe (for CodeRunner)
#cd WEBROOT
cd data/www/html
git clone https://github.com/trampgeek/jobe.git
git commit -am "Cloned Jobe from github"
git tag -a version1+coderunner+jobe -m 'version1 with CodeRunner and Jobe'
#sudo ./install

#push all to production repository
cd data/www/html
git push production $BRANCH

echo "<<<<<< All done >>>>>"
