#!/bin/sh

#create a directory called moodle
#cd to the newly created directory.
#change things according to your settings
mkdir ~/github/moodle
cd ~/github/moodle

#Initialize empty Git repository
git init

#register moodle.org as remote repository. 
git remote add upstream git://git.moodle.org/moodle.git

#add actechlab integration repository
git remote add integration git@actechlab.warwick.ac.uk:techteam/moodle_integration.git
#add actechlab production repository
git remote add production git@actechlab.warwick.ac.uk:techteam/moodle_production.git

echo "the following repositories where added:"
git remote

git fetch integration
#lists all available branches. 
echo "lists of all available branches." 
git branch -a

#create a new local branch called MOODLE_26_STABLE
#and set it to track the remote branch MOODLE_26_STABLE from the upstream repository.
#git branch --track MOODLE_26_STABLE integration/MOODLE_26_STABLE 
#Switches to the newly created local branch.
git checkout MOODLE_26_STABLE

echo "<<<<<< All done >>>>>"
