#!/bin/sh

#change according to your settings
cd ~/github/moodle
#keep my personal Moodle repository synced with the upstream repository.
#sammy_moodle is git@actechlab.warwick.ac.uk:techteam/sammy_moodle.git
#upstream is git://git.moodle.org/moodle.git

BRANCH=MOODLE_26_STABLE

git fetch upstream
git push sammy_moodle upstream/$BRANCH
