#!/bin/sh
#**********
#This script is for syncing only
#Not for first time creation of a branch
#If BRANCH doesn't exist on the remote repository, 
#git will come back with an error
#**********
cd /data/www/html
#keep the standard Moodle branch at actechlab repository synced with the upstream repository.
#ntegration is git@actechlab.warwick.ac.uk:moodle/integration.git
#upstream is git://git.moodle.org/moodle.git
git fetch upstream
BRANCH=MOODLE_26_STABLE
#If BRANCH doesn't exist on the remote repo, 
#git will come back with an error
git push integration refs/remotes/upstream/$BRANCH:$BRANCH
