#!/bin/sh

#change according to your settings
cd ~/github/moodle
#keep my Moodle repository at actechlab synced with the upstream repository.
#sammy_moodle is git@actechlab.warwick.ac.uk:techteam/sammy_moodle.git
#upstream is git://git.moodle.org/moodle.git

#The 2 first lines n the loop avoid an error if 
#$BRANCH doesn't exist on my personal repo
BRANCH=MOODLE_26_STABLE
git push sammy_moodle $BRANCH:$BRANCH

git fetch upstream
for BRANCH in MOODLE_26_STABLE; do
	git push sammy_moodle refs/remotes/upstream/$BRANCH:$BRANCH
done
